### ISSUE TITLE
Failed build on Windows 7x64 OS

### ISSUE THREAD

**Issue by cookch10** [coveo/nashorn-commonjs-modules#28]
I recently downloaded version `1.0.9` and attempted to build the project, but was met with unit test failures.

I tried to compile by running `mvn package`, and was met with the following test failures:
Failed tests:
rootFolderHasTheExpectedProperties(com.coveo.nashorn_modules.FilesystemFolderTest)
getFolderReturnsAnObjectWithTheExpectedProperties(com.coveo.nashorn_modules.FilesystemFolderTest)

Tests run: 68, Failures: 2, Errors: 0, Skipped: 0

OS info:
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: C:\apache-maven\bin\..
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: C:\Progra~1\Java\jdk1.8.0_102\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

Any insight into what might be going wrong would be appreciated!

**Comment by cookch10** [comment]
It seems the unit tests looking at the path information don't account for Windows OS, which have paths in the format of drive:\path\someotherpath.  While I can disable these tests to get the build to completion, the larger question is, is the fact that these tests are failing going to cause an issue with the library functionality?

**Comment by arisone** [comment]
Hi @cookch10 
I'm using this module on Windows and I've no issue. I think that the problem is how the class `FilesystemFolder `and the related test have been written. 

The `FilesystemFolder ` is a wrapper of a folder and when examining a path to a resource (referenced with the require call) it adds the character `'/'` when creating the subfolder wrapper. 
In Java working with this character as separator is "portable" both in Windows and in Unix like path style but after the creation of a `File `object the "universal separator" is converted in the style of the underlying system (see the property `File.separator`). So the test that fail is not "portable".

I think the correct way to write the test for the method `rootFolderHasTheExpectedProperties` (to test the class as it is written at the moment) could be:
```
  @Test
  public void rootFolderHasTheExpectedProperties() {
    assertTrue(root.getPath().startsWith(file.getAbsolutePath().replace(file.getPath(), "")));
    assertTrue(root.getPath().endsWith(file.getPath() + "/"));
    assertNull(root.getParent());
  }
```

Hope this helps.

**Comment by malaporte** [comment]
Thanks for the suggestion, I made a PR with your proposed change. It works on OS X, but I have no Windows machine to test it. I'll try spinning up a VM later, but @cookch10 if you can try it out and report your findings that would be very kind of you 😁

**Comment by arisone** [comment]
Hi @malaporte,
happy to hear you. If you are opened to my proposal I would like to be more drastic. I propose:
- in `FilesystemFolder` use `File.separator` instead of `"/"`
- in FilesystemFolderTest remove all assert based on string constants and use `File.getPath` and `File.separator` to:
   - to retrieve the root path, i.e <drive letter> on Win s.o. and / on POSIX s.o. then use this root path when assert `Folder.getPath.startsWith`
   - to assert `Folder.getPath.endsWith` 

I attach you the two modified files tested under Windows.
I'm very happy about your work and I'm willing to contribute more and more if possible ;)
Bye
arisone

[FilesystemFolderAndTest.zip](https://github.com/coveo/nashorn-commonjs-modules/files/1470379/FilesystemFolderAndTest.zip)

**Comment by cookch10** [comment]
I tested it with your change @malaporte , however, I still get one failing test:
Failed tests:   getFolderReturnsAnObjectWithTheExpectedProperties(com.coveo.nashorn_modules.FilesystemFolderTest)

Tests run: 68, Failures: 1, Errors: 0, Skipped: 0

**Comment by arisone** [comment]
Hi @cookch10 it fails for the same reason.
In this comment [more drastic solution](https://github.com/coveo/nashorn-commonjs-modules/issues/28#issuecomment-344217632) I've proposed a change both on class and on test which should fix the issue.

**Comment by cookch10** [comment]
@arisone, are you planning on submitting a PR with your suggested changes?  Wondering if I should open one up, but don't want to duplicate efforts.  Thanks!

**Comment by malaporte** [comment]
Thanks a lot @arisone for the fix, much appreciated!

**Comment by arisone** [comment]
You are welcome @malaporte. Thanks a lot to you for the great work you've done with this project.

**Comment by cookch10** [comment]
Thanks @malaporte and @arisone!  A great project indeed.
